name: LifeMoreMythicMobs
version: @version@
main: net.azisaba.lifemoremythicmobs.LifeMoreMythicMobs
api-version: 1.15

depend: [MythicMobs]
load: STARTUP

commands:
  lmmm:
    aliases: [lmm]
    permission: lifemoremythicmobs.lmmm
    description: Main command of LifeMoreMythicMobs
